### ISSUE TITLE
Biblioteca GTK+

### ISSUE THREAD

**Issue by Crowexe** [Crowexe/Proyecto-1CV10#2]
@norman-ipn, profesor, para la instalción de gtk+, ¿Qué comando debo usar? Ya descargué como 3 y al momento de compilar me manda que esa biblioteca no la tengo

**Comment by norman-ipn** [comment]
El comando para instalar es:
`sudo apt install libgtk-3-dev glade`
Para compilar revisa el ejemplo que subí a mi repositorio de estructuras de datos.
